#!/opt/homebrew/bin/zsh

# ONLY WORKS ON THE MACBOOK PRO WITH EXTERNAL MONITOR, NOT ON THE BUILT-IN DISPLAY
# ALSO ONLY WHEN ALREADY CASTING, NOT WHEN CASTING IS STARTED FROM SCRATCH

cliclick -f - << EOF
m:1710,10
c:+0,+0
w:500
m:-40,+370
c:+0,+0
w:500
EOF


